version: '3'
service:
    image-album-service:
        image: image-album-service
        build: ./ImageAlbumService
        command: ["go", "run", "main.go"]
        ports: 
            - "8050:8050"
        depends_on: 
            - db
        links: 
            - db
    image-storage-service:
        image: image-storage-service
        build: ./ImageStorageService
        command: ["go", "run", "main.go"]
        ports: 
            - "8051:8051"
        depends_on: 
            - db
        links:
            - db
    db:
        image: postgres
        ports:
            - 5432
